// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxUK9eDmub2HeBv2EQjj-TADGo34tKlQ',
    appId: '1:277298053642:web:885ef2705ce02cacdd95f3',
    messagingSenderId: '277298053642',
    projectId: 'fir-auth-app-d407c',
    authDomain: 'fir-auth-app-d407c.firebaseapp.com',
    storageBucket: 'fir-auth-app-d407c.firebasestorage.app',
    measurementId: 'G-2FXWB35N4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD06GIDDVdK26lfoOpMWUxV7M3fniMjxjA',
    appId: '1:277298053642:android:d0d0b3d7cd4c88b7dd95f3',
    messagingSenderId: '277298053642',
    projectId: 'fir-auth-app-d407c',
    storageBucket: 'fir-auth-app-d407c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOxUK9eDmub2HeBv2EQjj-TADGo34tKlQ',
    appId: '1:277298053642:web:bf9bd1016dc2f00cdd95f3',
    messagingSenderId: '277298053642',
    projectId: 'fir-auth-app-d407c',
    authDomain: 'fir-auth-app-d407c.firebaseapp.com',
    storageBucket: 'fir-auth-app-d407c.firebasestorage.app',
    measurementId: 'G-PE3C6BT5HR',
  );
}
